eureka:
  instance:
    hostname: localhost
  server:
    enableSelfPreservation: false #自我保护模式关闭
    eviction-interval-timer-in-ms: 60000 #清理间隔（单位毫秒，默认是60*1000）
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${eurekaServerZone}